### ISSUE TITLE
Can't import using commonjs

### ISSUE THREAD

**Issue by aristidesfl** [foxbenjaminfox/vue-async-computed#1]
Add support for loading with CommonJS syntax too `AsyncComputed = require('vue-async-computed')`.

In the meanwhile a workaround is to use `AsyncComputed = require('vue-async-computed').default`

**Comment by foxbenjaminfox** [comment]
Sure, it makes sense to have support for CommonJS.

Luckily, it's only a babel plugin away.

I added the plugin to the project, so now it should properly work also with CommonJS.
