### ISSUE TITLE
Pass raw err to errorHandler callback

### ISSUE THREAD

**Issue by mdreizin** [foxbenjaminfox/vue-async-computed#10]
Hello,

It would be nice to use raw `err` in `errorHandler` callback:

Vue.use(AsyncComputed, {
  errorHandler(err) {
    console.log('Hey, an error!')
    console.log('---')
    console.log(err.message)
  }
)

**Comment by foxbenjaminfox** [comment]
I've added a new option, `useRawError`. If you pass a truthy value for that option it will pass the raw error object to the error handler.

**Comment by mdreizin** [comment]
@foxbenjaminfox Thanks a lot.
