### ISSUE TITLE
Doesn't seem to deep watch properties.

### ISSUE THREAD

**Issue by hybridwebdev** [foxbenjaminfox/vue-async-computed#101]
So I think i came across an issue where asyncComputed does not deep watch properties used in it. Consider the following:

```
export default {
    props: {
        /**
            The name of the connection. Eg connect/{connection name}
        */
        name: {
            type: String,
            default: false,
            required: true
        },
        /**
            The Map must be an array. It will be the fields returned from the connection.
        */
        map: {
            type: Object,
            default: false,
            required: true
        },
        /**
            The object can be any variable. It is used for the query portion of the connection.
        */        
        object: {
            type: ( Object, String, Number ),
            default: false,
            required: true
        },
    },
    render(h, ctx) {
        return this.$scopedSlots.relay( { data: this.data } )
    },
    asyncComputed: {
        data: {
            async get(){
                return await this.$vue_app.$connection( {
                    name: this.name, 
                    map: this.map, 
                    object: this.object, 
                } )
            },
            default: false,
        }
    }
}
```

As you can see, we have 3 properties that are used in the async computer getter. However, if these are deeply nested objects the async computed method is not recalled.

So my question is, is this intended behavior, or an oversite. Of course you can always add a manual refresh trigger via a watch on the properties, however this sorta defeats the purpose of using async computed.

Btw, thanks for such a great plugin. For now, my watcher works, but it would be nice to be able to figure out this issue and a cleaner solution.

**Comment by foxbenjaminfox** [comment]
I can't quite tell what's going on in your example: for one thing, where is the deeply nested object access that is causing the problem?

The way `asyncComputed` works behind the scenes is using Vue's normal `computed` mechanism: the function for computing an `asyncComputed` property is used internally as a normal `computed` function (one whose return value is a `Promise`, of course.) What this means is that the function is re-run and the result recalculated _exactly_ in the same circumstances as it would be if it were a function for computing a normal Vue computed property.

Could you perhaps put together a [codepen](https://codepen.io/) or the like to show this issue in action? A simple example of an async computed property (with a deeply nested object) that isn't being properly updated, that is. If I could see a simple example of this in action, I will be able to figure out to what extent this is a real bug.

**Comment by hybridwebdev** [comment]
It seems I may have jumped the gun on opening this ticket. According to my tests, it does indeed work as expected in an isolated environment: https://codesandbox.io/s/crazy-feather-qkv1c?file=/src/App.vue

That's a loose simulation of what i'm doing. However, my actual implementation is slightly different and too complex/private to dive into on here.

I had theorized after looking at your code, that my issue may have been because I was using a renderless wrapper component, and this was somehow not playing well with the should/update hooks. However, after testing I believe the side-effect may be a result of my actual live implementation of it.
