### ISSUE TITLE
vue@2.2.5,use has error

### ISSUE THREAD

**Issue by AaronChen2012** [foxbenjaminfox/vue-async-computed#14]
use create dialog,with this way
import Vue from 'vue'
let DialogConstructor = Vue.extend(require('./main.vue'))

let instance;

var Dialog = function(options) {
	instance = new DialogConstructor({
    	data: options
  	});
	instance.vm = instance.$mount();
	document.body.appendChild(instance.vm.$el);
	instance.vm.show = true;
	return instance.vm;
}
export default Dialog;

can not execute async-computed

**Comment by foxbenjaminfox** [comment]
Care to give some more information about the error you receive? The code you provide doesn't use `vue-async-computed` at all. As it is, from the information provided, I can't debug your code for you. But it seems unlikely to be directly related to `vue-async-computed`.

**Comment by AaronChen2012** [comment]
demo:http://jsrun.net/8ekKp/edit

**Comment by AaronChen2012** [comment]
it means use Vue.extend,then can`t execute asyncComputed.

**Comment by foxbenjaminfox** [comment]
Sorry for the delay in getting back to you. As of v3.1.1, I have fixed a problem with the way `vue-async-computed` was handling the `asyncComputed` object, so it should now traverse the prototype chain properly. This means that it should now work as expected with `Vue.extend`.

**Comment by AaronChen2012** [comment]
thinks
