### ISSUE TITLE
server-side rendering

### ISSUE THREAD

**Issue by Alphmega** [foxbenjaminfox/vue-async-computed#20]
Looks like it does not support server-side rendering, Any plans about adding server-side rendering as a new feature in the short term ?

**Comment by dinony** [comment]
Can confirm that.. I have a SSR app setup via Nuxt and the async computed property is recomputed on the client side.

**Comment by foxbenjaminfox** [comment]
This isn't something its easy to add support for, with the current way `vue-async-computed` works.

I'm going to close this issue now, but as always I'm happy to receive PRs, so if anyone wants to take a shot at adding support for this, feel free.

**Comment by alfredriesen** [comment]
With 2.6 it would be possible to use the new introduced serverPrefetch hook
