### ISSUE TITLE
'default' keyword

### ISSUE THREAD

**Issue by crimaniak** [foxbenjaminfox/vue-async-computed#21]
'default' is javascript keyword, so es-lint failed with 'Parsing error: Unexpected token' error. I think it's better to use another key for this, like 'defaultValue'.

**Comment by foxbenjaminfox** [comment]
What version of eslint are you using? `default` is perfectly valid as a property name, although it is indeed reserved as an identifier. Way back in ES3 there was an issue with needing to quote such property names, but that hasn't been an issue for years. It works in all browsers that Vue itself is compatible with.

In short, I think this is more a problem related to a misconfiguration of your linter, and not an actual issue.

If you have a case where this is actually a problem, I'll reconsider adding another key (such as `defaultValue`) which can be an alias for `default`, but for now I'm closing this issue.
