### ISSUE TITLE
Add to Bower?

### ISSUE THREAD

**Issue by WillFM** [foxbenjaminfox/vue-async-computed#22]
Would be extremely helpful if this repo was configured for bower:

https://bower.io/docs/creating-packages/

**Comment by n1ru4l** [comment]
Just sayin: https://twitter.com/bower/status/844615305406169095

Any reason why you prefer bower over npm?

**Comment by WillFM** [comment]
Would have made life easier with current workflow. Being I'm currently using bower for everything else related to Vue. After reading some status on bower though, it appears there in a "Maintenance only" lifestyle, nearing end of life as far as the service goes. So it looks as if I might need to update my workflow as a whole anyway.
