### ISSUE TITLE
not work with vue 2.3.4

### ISSUE THREAD

**Issue by djvonavi** [foxbenjaminfox/vue-async-computed#26]
can U help me? I install it, but Vue instance not have in computed props my async prop

**Comment by GeekJosh** [comment]
Working fine for me in 2.5.2 so either there was a breaking change that has now been resolved or there's an issue with your code - if you share it I'm happy to take a look for you

**Comment by Xosmond** [comment]
Also for me on v2.5.13 is working fine.
