### ISSUE TITLE
Compatibility with Vue.js 2.0?

### ISSUE THREAD

**Issue by kincaidoneil** [foxbenjaminfox/vue-async-computed#3]
After simply installing the plugin with `Vue.use()`, it throws an error: `Uncaught TypeError: this._initComputed is not a function`. I'm using Vue.js 2.0 RC-4, so I *assume* that's causing the issue. Is adding compatibility for 2.0 on the horizon, or is the issued caused by something else?

Thanks--love the plugin!

**Comment by foxbenjaminfox** [comment]
Quite right. This package uses some Vue internals that have been changed quite a bit between version 1.0 and 2.0.

Adding compatibility for 2.0 is certainly on the horizon. Specifically, I'm waiting for the final version of Vue 2.0 to be released. But as soon as it is I intend to make this plugin compatible with it. (Or rather, I intend to write a new version of this plugin which will be compatible with Vue 2.0. It will have to be more of a rewrite than an upgrade, as Vue's internals have changed quite a bit.)

**Comment by foxbenjaminfox** [comment]
I've published a release candidate, tagged `next`. Barring major changes to the Vue internals, this is more or less the version I will release after Vue 2.0 is published.

Nevertheless, the standard disclaimer applies. You probably shouldn't use this in production yet, at least unless you really know what you're doing.

But if you want to try it out with Vue 2.0, you can `npm install vue-async-computed@next`, and it will work.

**Comment by foxbenjaminfox** [comment]
The latest version of `vue-async-computed` is now the Vue 2.0 compatible rewrite. You now should have no trouble at all with using this plugin with Vue 2.0.
