### ISSUE TITLE
I think computed method shouldn't have side effect

### ISSUE THREAD

**Issue by duxinxiao** [foxbenjaminfox/vue-async-computed#30]
Thanks for all of your work, but I think making computed method async is anti vue's design. In my opinion, I think computed method shouldn't change any state or make api call. If you must, I think you'd better use 'watch' instead.

**Comment by foxbenjaminfox** [comment]
Well, you certainly don't have to use `vue-async-computed` if you don't want to :smile:.

Not every Vue plugin fits with everybody's preferred style, so it's perfectly fine that this one doesn't fit with yours. For what it's worth, I agree with you that computed methods shouldn't try to avoid changing state, either locally or remotely. But there's still plenty of room for making API calls that are [safe and idempotent](https://tools.ietf.org/html/rfc7231#section-4.2), such as HTTP GET requests.

Such computed properties are, in my opinion, not really any less pure than ones which depend purely on local state. Yes, behind the scenes there is some hidden state (that `vue-async-computed` is handling for you), but the end result is an abstraction that let's you treat it just as purely and unstatefully as any local data.

I think there is power in such abstractions. Vue its]elf [keeps](https://github.com/vuejs/vue/blob/653aac2c57d15f0e93a2c1cc7e6fad156658df19/src/core/observer/watcher.js) and [modifies](https://github.com/vuejs/vue/blob/653aac2c57d15f0e93a2c1cc7e6fad156658df19/src/core/observer/dep.js#L51-L58) some hidden state when watching for data changes, and that's fine: the interface that it exposes uses these implementation details behind the scenes, but doesn't expose them.

My goal is for `vue-async-computed` to do much the same. I like to think that I managed, and that the result is useful. I even think that it functions in much the same ways as Vue's [internals](https://github.com/vuejs/vue/blob/653aac2c57d15f0e93a2c1cc7e6fad156658df19/src/core/observer/watcher.js), and so is very much in sync with Vue's philosophy.

Of course, it's OK to disagree: if you feel that you don't want to use this plugin, there's nothing wrong with that, and you are certainly free to write your own Vue applications in whatever way you feel is best for you. But I do hope that you understand a bit better now, after my explanation, why I don't think that there is anything wrong with asynchronous computed methods, if used responsibly.

**Comment by duxinxiao** [comment]
Thanks for your patiently reply, I get a better understanding of your design purpose. I think it fine to handle GET requests or something like that ( just like you said, you handle the hidden state for users, make a easy to use api ). It's cool to share your thoughts, thanks for your work
