### ISSUE TITLE
Is it possible to set the default value of an asyncComputed property?

### ISSUE THREAD

**Issue by zuperm4n** [foxbenjaminfox/vue-async-computed#31]
I am using this plugin to render a dynamic list which updates when other properties in the component change.

In my view I have a simple check to see if the computer value has a length of zero to display a "No results message":
```
<tr v-if="list.length < 1" class="no-results">
    <td colspan="10" class="has-text-centered">No results</td>
</tr>
```

However, by default, when the component initialises the value for `list` is `null` which throws an error saying that the property `length` of `undefined`is not found. Is there any way to set the default value of a computed property? I'd like to avoid filling my view with multiple checks for if the property is `null` or has a length less than one.

I noticed it's possible to [set the global default value](https://github.com/foxbenjaminfox/vue-async-computed/issues/13), but I don't think this approach will work for me as in other components I am expecting the value to be `null`.

**Comment by zuperm4n** [comment]
Whoops, I clearly didn't look at the Issues history before posting... (I blame the not-so-obvious title!)

https://github.com/foxbenjaminfox/vue-async-computed/issues/9

**Comment by foxbenjaminfox** [comment]
For future reference: The second and third code examples of the [usage](https://github.com/foxbenjaminfox/vue-async-computed#usage-example) section of the README demonstrate exactly what you were looking for: setting the default value for an individual computed property.

I'm glad you found the solution, even if your had a slightly indirect route to finding it.  :smiley:
