### ISSUE TITLE
Endless loop on navigation back to page with async-computed

### ISSUE THREAD

**Issue by dsl101** [foxbenjaminfox/vue-async-computed#49]
I have a computed prop that depends on getting something from firestore, so vue-async-computed seemed like a perfect way to get this into my component. But, I've hit a snag I've not seen before when navigating back to a page that previously had successfully loaded the async value.

My app has 2 routes (`/` and `/<projectId`), and when on a 'project' page, the user can navigate back to the 'home' page which lists all projects.

On the home page, I have this template and computed:

```
<template>
  <q-page padding>
    <div class="q-headline">Projects:</div>
    <q-list link >
      <q-item v-for="(project, projectId) in asyncAllProjects" :key="projectId"
        @click.native="$router.push(`/${projectId}`)"
      >
        {{project.data().name}}
      </q-item>
    </q-list>
  </q-page>
</template>
.
.
.
    asyncComputed: {
      asyncAllProjects: {
        lazy: true,  // Don't get until binding is done
        async get () {
          console.log('Index: Calling asyc allProjects()...')
          const ap = await this.allProjects()
          console.group('Index: All Projects:', ap)
          _.forEach(ap, (doc, key) => { console.log(key, ':', doc.data()) })
          console.groupEnd()
          return ap
        }
      }
    },
```

The `getter` for that calls firebase. Note I've hard coded it to fetch a single project to help with testing:
```
export const allProjects = () => getters => {  // Must be a function, or it's called early to evaluate
  console.log('→SG Getting allProjects...')

  const docId = 'DalEtsuauL46a9bpSKRH'
  return firebase.firestore().collection('projects').doc(docId).get().then(snapshot => {
    console.log('→SG snapshot:', snapshot)
    return {[docId]: snapshot}
  })
}
```

On first page load, all works fine, and the projects are listed. I can then click on one and navigate to the project page. But when I navigate _back_ to the home page, the console fills with endless log info from the above, repeatedly calling the getter until it runs out of energy and crashes. At the very start of that endless logging output, I can see that the getter is called _twice_ for some reason:
```
13:07:38.909 Index.vue?b484:25 Index: Calling asyc allProjects()...
13:07:38.909 getters.js?2e7d:19 →SG Getting allProjects...
13:07:38.912 Index.vue?b484:25 Index: Calling asyc allProjects()...
13:07:38.913 getters.js?2e7d:19 →SG Getting allProjects...
```
and after that the rest of the logs show endless calls / returns. One thing I did notice via Vue devtools is that on first load, the component has these properties:

![image](https://user-images.githubusercontent.com/900542/46868438-41063000-ce20-11e8-9969-75080eca429c.png)

but on returning to that page it looks like this:

![image](https://user-images.githubusercontent.com/900542/46868462-4fece280-ce20-11e8-8183-9310cebdd210.png)

I can't tell if that's a symptom or pointing towards a cause. Any ideas which the asyn-computed would be triggered multiple times?

**Comment by foxbenjaminfox** [comment]
Whenever something that the getter depends on is updated, that causes the getter to be re-run. (Just like Vue's normal synchronous computed properties.) The reason why you shouldn't pass firebase snapshots back to the getter is that those snapshots are updated "live", and so if the getter uses it, then each time it's updated, then Vue's reactivity system causes the getter to run again.

That's my guess about what the cause here is. The solution is, as you have already figured out, to have the getter not use the live-updating firebase result object, but rather the static version of that object, which you fetched with `.data()`.
