### ISSUE TITLE
Plugin does not handle watching of data that is updated asynchronously in a methods: function with a Promise inside

### ISSUE THREAD

**Issue by tarngerine** [foxbenjaminfox/vue-async-computed#61]
I'm not sure if this was intentional out-of-scope, or I am using the plugin incorrectly, but let's say you have some component like this:

```
data: {
  friends: [],
  selectedIndex: 0
},
methods: {
  load: function() {
    return fetch('someurlhere').catch(...).then(res => {
      this.friends = res.data.friends // this is being set async, and the value is correct
    })
  }
},
created: {
  this.load()
},
asyncComputed: {
  selectedFriend() {
    return new Promise(resolve => resolve(this.friends[this.selectedIndex])
  }
}
```

In this case, the `selectedFriend` property is not being properly updated when `this.friends` is updated in the Promise. Yes, `this.friends` has the correct data, it's just not triggering a recompute when it's set in `load()`.

FWIW, I can make this work properly by using multiple `watch:` methods on `this.friends` and `this.selectedIndex`, but I was hoping for a cleaner solution.

**Comment by tarngerine** [comment]
Nevermind, it was another issue, not async related!

**Comment by molvqingtai** [comment]
I want to know how you solved this problem?
