### ISSUE TITLE
[BUG] 3.5.1 need to remove the `module` attribute immediately, it breaks webpack build

### ISSUE THREAD

**Issue by adamchenwei** [foxbenjaminfox/vue-async-computed#62]
Is `module` a standard property, @mtorromeo? because so far I see its not but only for rollbar. https://stackoverflow.com/questions/42708484/what-is-the-module-package-json-field-for
Also, this is breaking IE11 support because its importing esm version that does not compile `function` properly. In `module`, its using es6 formating (i.e. in compiled js, we have `get()` instead of correct way of `function get()`) 
Please remove this config from the package.json if possible. thank you.

ref line: https://github.com/foxbenjaminfox/vue-async-computed/commit/9e2d04684f1aea19658f01202153fca839c3d906#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R6

**Comment by mtorromeo** [comment]
It's used by bundler tools, so if you want you can configure your own build pipeline to transpile it with babel for example.

**Comment by foxbenjaminfox** [comment]
I've released v3.5.2 which transpiles also `dist/vue-async-computed.esm.js` (the `module` file.)

@mtorromeo: Yes, definitely. But I do see that it seems that other projects do transpile the file they list as `module` in `package.json`, and it does seem that some people do rely on that. It seems worthwhile to support that use case as well. It's a [fairly simple change](https://github.com/foxbenjaminfox/vue-async-computed/commit/15150de00388f1e1aee20bab051deb4a6d346bc2) to the build step to also transpile that file.
