### ISSUE TITLE
feature request - debounce asyncComputed

### ISSUE THREAD

**Issue by d1manson** [foxbenjaminfox/vue-async-computed#8]
It would be nice to be able to define a computed function which waits for 0 or more milliseconds before issuing the compute request, and provides various options for what happens if subsequent requests arrive during that delay.

I'm using `asyncComputed` currently with `fetch`, but I want to throttle the number of fetch requests being made, and show a "working..." temporary output or something.

Thanks!

**Comment by foxbenjaminfox** [comment]
That does indeed sound like a useful thing to be able to do.

I don't think you need any particular help from this plugin to do it though. Already, you can write something like this, using any promise-based debounce, for instance as provided by the `debounce-promise` package:

````js
const debounce = require('debounce-promise')

new Vue({
  asyncComputed: {
    myProperty: debounce(function () {
      // The function body, which returns a promise
    }, 100)
  }
}
````

Debouncing the function passed to `vue-async-computed` does not require any particular changes to the plugin.

On the other hand, I don't know off the top of my head of a simple way to do what you want with regards to showing the placeholder value while the debouncing is going on. It is true that it seems like that could be a useful feature. That said, it's more a feature for a debouncing library than for this plugin directly. It's more of a generic debouncing feature than anything specifically to do with Vue.

That said, I'm not against adding that sort of thing if it would simplify matters, although perhaps I'd add it in a separate library as most users of `vue-async-computed` won't need it and it would be a shame to bulk `vue-async-computed` up with things not directly related to Vue.

**Comment by d1manson** [comment]
Thanks for the reply - you are absolutely right about all your points!
(although for the time being I have just written a basic custom bit of code inside the `asyncComputed`.

Nice library by the way! ;)

**Comment by diachedelic** [comment]
Even with `{ leading: true }` set for `debounce()` (which should cause it to run its fn immediately), this approach only calls the internal function once or twice.  Further calls are unresponsive.

```
<template>
  <div class="event-list">
    <h1>Events</h1>
    <select v-model="filter">
      <option value="mine">My events</option>
      <option value="all">All events</option>
    </select>
    <input type="text" v-model="query" placeholder="Search" />
    <hr />
    <ul>
      <li v-for="result in results">
        {{ result.title }}
      </li>
    </ul>
  </div>
</template>

<script>
import { api } from '@crosscountryapp/xhr'
import debounce from 'debounce-promise'
import YouAreI from 'youarei'

export default {
  data: () => ({
    filter: 'mine',
    query: '',
  }),
  asyncComputed: {
    results: {
      get: debounce(function() {
        const url = new YouAreI()
        const q = this.query.trim()

        if (this.filter === 'mine') {
          url.pathSet('/events/_search/mine')
        } else if (q) {
          url.pathSet('/events/_search')
        } else {
          url.pathSet('/events/_search/all')
        }

        if (q) {
          url.queryMerge({ q })
        }

        return api({
            path: url.toString(),
            authToken: this.$store.state.authToken,
          })
          .then(body => body.results)
          .catch(err => {
            console.log(this)
            console.log(this.filter)
            console.error(err)
          })
      }, 500),
      default: [],
    },
  },
}

</script>
```

**Comment by disarticulate** [comment]
I tried this with quasar's debounc function and all I'm getting is a reference to debounced() and not a value.

**Comment by foxbenjaminfox** [comment]
@disarticulate: you need to use a promise-aware debounce function, one that debounces based on the value the promise resolves to, not the promise object itself.

For example, one implementation of that you could use is the [`debounce-promise`](https://github.com/bjoerge/debounce-promise) package.

**Comment by geekytime** [comment]
I'm having the same problem as @diachedelic. 🤔 

Everything works great until I try to `debounce` the getter function, and then it stops reacting to changes in other properties. I am also using `debounce-promise`.

**Comment by geekytime** [comment]
I think the `debounce`d function is failing to react because Vue cannot "hear" the the accessors to my other computed values from inside the debounce function wrapper. If I create the `debounce`d function outside the Vue instance, and pass any computed values into the wrapper, it works:

```javascript
const fetchItems = debounce(function () {
  const response = await api.get({
    url: '/some/url',
    params: this.params
  })
  return response.results
})

const vm = new Vue({
  data: {
    showing: 'all',
    name: '',
  },
  computed: {
    params () {
      return {
        showing: this.showing,
        name: this.name
      }
    }
  },
  asyncComputed: {
    items: {
      default: [],
      lazy: true,
      async get () {
        return fetchItems(this.params)
      }
    }
  }
})
```
