### ISSUE TITLE
Depend  async computed on async computed

### ISSUE THREAD

**Issue by felixoi** [foxbenjaminfox/vue-async-computed#86]
My current setup looks like:

```javascript
        asyncComputed: {
            project() {
                return API.request('projects/' + this.pluginId);
            },
            fullSlug: function () {
                return this._async_computed$project.then(project => project.namespace.owner + "/" + project.namespace.slug);
            }
        },
```
So my second async computed value depends on the first one. This code works, but it's pretty ugly. Is there a way to do this better with this library? If not this would be a feature request.

**Comment by foxbenjaminfox** [comment]
> Is there a way to do this better with this library?

Of course! In fact, I would say that the whole point of this library is that it lets you ignore the fact that behind the scenes you're working with promises, and just work with properties of the Vue object directly as if everything is synchronous.

The one thing to keep in mind is that `this.project` will be `null` until the API request resolves. Having to handle the `null` case isn't a bug or a problem: you always need to take into consideration how things will work until the data arrives.

So all things considered, this is the way I'd write it:


```javascript
asyncComputed: {
  project() {
    return API.request('projects/' + this.pluginId);
  },
  fullSlug() {
    if (!this.project) return null;
    return this.project.namespace.owner + "/" + this.project.namespace.slug;
  }
},
```

This will work exactly as you'd like it to, exactly the same as the code you gave as your current set up. (Even up to the point of `fullSlug` being `null` until the promise returned from `project` resolves. The beauty of this library is that it lets you write code this way, as if your `asyncComputed`s were just ordinary computed properties.

**Comment by felixoi** [comment]
Makes sense. Thanks.

**Comment by covert8** [comment]
Hi i'm having some issues using above described method.
`getUserName: {
      async get() {
        let usr = await this.user;
        if (!this.user) return null;
        return this.user.userName;
      }
    },
    user() {
        return this.$axios
          .get(this.apiurl + "/user/info")
          .then(resp => resp.data);
    },
`
The getUserName property just returns undefined. Some guidance would be appreciated if anyone has any idea's. Current workaround is to make user a normal method.
