### ISSUE TITLE
TypeScript support in 3.8.0

### ISSUE THREAD

**Issue by nwtgck** [foxbenjaminfox/vue-async-computed#87]
Hi, @foxbenjaminfox! Thank you very much for support TypeScript officially.

I just tried vue-async-computed@3.8.0 in TypeScript. Could you tell me how to import `AsyncComputed `? I tried several ways to import it, but not successful.

And, I found published vue-async-computed@3.8.0 in my `node_modules` has no `types/` directory. Is this OK?
![image](https://user-images.githubusercontent.com/10933561/71386955-a4027200-2634-11ea-94ef-61ed4b882acc.png)

**Comment by foxbenjaminfox** [comment]
Thanks for pointing that out. It seems that I made a mistake, and forgot to add the `types` directory to the list of published directories in `v3.8.0`. I've released a `v3.8.1` release which fixes this.

Please let me know if it works for you properly now.

**Comment by nwtgck** [comment]
@foxbenjaminfox Thank you very much. It seems the type definition problem was fixed.

I'm not sure the correct usage in TypeScript. I imported like the following.

```ts
import AsyncComputed from "vue-async-computed";
```

, and I have the error below. I found `AsyncComputed` is a class. It is not a decolator any more? I could not find a document to know how to use vue-async-computed in TypeScript.

![image](https://user-images.githubusercontent.com/10933561/71409689-d4263100-2685-11ea-877c-08d74a969560.png)

**Comment by foxbenjaminfox** [comment]
OK, I'm glad that `v3.8.1` now works. I could definitely export the `IAsyncComputedValue` interface if you want to use it to write a decorator, but I'll actually do you one better: if you'd like to open a PR with your decorator, I'd be happy to merge it. That way everyone else can also benefit from the decorator as well.

All things said, I'm happy to take contributions to this or indeed to any part of `vue-async-computed`, but it is rather unlikely that I'll end up adding anything typescript-related myself.

**Comment by nwtgck** [comment]
@foxbenjaminfox Thanks! I made #88.
