### ISSUE TITLE
default as function

### ISSUE THREAD

**Issue by mdreizin** [foxbenjaminfox/vue-async-computed#9]
Hello,

It would be nice to use function for getting default value:

```js
new Vue({
  data: {
    postId: 1
  },
  asyncComputed: {
    blogPostContent: {
      get () {
        return Vue.http.get('/post/' + this.postId)
          .then(response => response.data.postContent)
       },
       default: () => `Loading post ${this.postId}...`
    }
  }
}
```

**Comment by foxbenjaminfox** [comment]
The main issue with this is that currently, the default values are set in the `beforeCreated` hook, so in your example it would be called before `this.postId` is set. (Putting aside the slight error in the example you gave: The arrow function has a lexically scoped `this`, so `this.postId` wouldn't refer to what you'd want it to regardless. But that's a separate matter.)

So, what are the options? Well, I could move the computation of the defaults to the `created` hook instead. That would mostly work, but it would technically be a breaking change. I could move only function defaults to the `created` hook, but that would be confusing.

Unless I can think of a better idea, I'll probably choose the first option, which would necessitate a major version bump, but that's not the end of the world. Still, I'd rather avoid breaking backwards compatibility needlessly, even if almost no one is relying on the defaults already being defined before their `data` function is called.

**Comment by foxbenjaminfox** [comment]
I've just released a new version including this feature. Thanks!

**Comment by mdreizin** [comment]
@foxbenjaminfox Thank you for quick implementation of this feature ;)
