### ISSUE TITLE
how to use this plugin with class based vue components?

### ISSUE THREAD

**Issue by bruceauyeung** [foxbenjaminfox/vue-async-computed#94]
this is a really amazing plugin, but i am wondering how to use it with class(such as TypeScript Class) based vue components

**Comment by mustafakibar** [comment]
vue-async-computed-decorator

**Comment by bruceauyeung** [comment]
@mustafakibar i have a problem with  `vue-async-computed-decorator` plugin, i fired an issue: https://github.com/foxbenjaminfox/vue-async-computed-decorator/issues/8 

would you mind  take a look ?
